name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Match your local Node.js version

      - name: Install Dependencies
        run: npm install # Only if package.json exists in the root

      - name: Build
        run: echo "No build step required" # Replace if you add a build script
        # If using a build tool like Vite, add: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Use ./client if deploying from client directory
